name = "social-backup"
main = "functions/scheduled.ts"

compatibility_date = "2024-02-22"

kv_namespaces = [
  { binding = "SETTINGS", id = "settings" },
  { binding = "BACKUP_STATUS", id = "backup_status" }
]

[triggers]
crons = ["0 */2 * * *"]

[env.dev.triggers]
crons = ["*/1 * * * *"]